// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekadbwyhiagzuqekddeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrYWRid3loaWFnenVxZWtkZGVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMDQ2ODYsImV4cCI6MjA2NTc4MDY4Nn0.wdfn-86fFjYK1rGM4sST1eZ3LKBYH7p0JRjacMzOMwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);